// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5aUGE04vkKIzeuupQ3uNNb6Fg_ol-vs',
    appId: '1:316516565076:web:68f256c00bad67e230adc1',
    messagingSenderId: '316516565076',
    projectId: 'bitirmetezi-66376',
    authDomain: 'bitirmetezi-66376.firebaseapp.com',
    databaseURL: 'https://bitirmetezi-66376-default-rtdb.firebaseio.com',
    storageBucket: 'bitirmetezi-66376.firebasestorage.app',
    measurementId: 'G-7ZK6MLMMER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf2ybTX3ve_mZ4Dt-OGE7RNMmLA0FcYc',
    appId: '1:316516565076:android:85a734db42d151b830adc1',
    messagingSenderId: '316516565076',
    projectId: 'bitirmetezi-66376',
    databaseURL: 'https://bitirmetezi-66376-default-rtdb.firebaseio.com',
    storageBucket: 'bitirmetezi-66376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJcBWLWfu8hZEL6Q3_38yAZTY8MrtqYBE',
    appId: '1:316516565076:ios:f673f83622a1bdcd30adc1',
    messagingSenderId: '316516565076',
    projectId: 'bitirmetezi-66376',
    databaseURL: 'https://bitirmetezi-66376-default-rtdb.firebaseio.com',
    storageBucket: 'bitirmetezi-66376.firebasestorage.app',
    iosBundleId: 'com.example.bitirmetezimobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJcBWLWfu8hZEL6Q3_38yAZTY8MrtqYBE',
    appId: '1:316516565076:ios:f673f83622a1bdcd30adc1',
    messagingSenderId: '316516565076',
    projectId: 'bitirmetezi-66376',
    databaseURL: 'https://bitirmetezi-66376-default-rtdb.firebaseio.com',
    storageBucket: 'bitirmetezi-66376.firebasestorage.app',
    iosBundleId: 'com.example.bitirmetezimobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr5aUGE04vkKIzeuupQ3uNNb6Fg_ol-vs',
    appId: '1:316516565076:web:762b288ba9fae47530adc1',
    messagingSenderId: '316516565076',
    projectId: 'bitirmetezi-66376',
    authDomain: 'bitirmetezi-66376.firebaseapp.com',
    databaseURL: 'https://bitirmetezi-66376-default-rtdb.firebaseio.com',
    storageBucket: 'bitirmetezi-66376.firebasestorage.app',
    measurementId: 'G-TH6MHBRF2G',
  );

}