// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABY0_S6loAbNHJAjxUjCLzXpT2i1ypstY',
    appId: '1:344041336788:web:0f75fc502403ba6f7db041',
    messagingSenderId: '344041336788',
    projectId: 'bitirmetezi-7d032',
    authDomain: 'bitirmetezi-7d032.firebaseapp.com',
    storageBucket: 'bitirmetezi-7d032.firebasestorage.app',
    measurementId: 'G-N7EB0344MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEx5aKbje1MLy9VBUL_hTs0rsrk2RuVCs',
    appId: '1:344041336788:android:6670667d5281c8da7db041',
    messagingSenderId: '344041336788',
    projectId: 'bitirmetezi-7d032',
    storageBucket: 'bitirmetezi-7d032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeByybyjT666Ygk-ZFSUM96gm7SyeSkM',
    appId: '1:344041336788:ios:3483b80531c864587db041',
    messagingSenderId: '344041336788',
    projectId: 'bitirmetezi-7d032',
    storageBucket: 'bitirmetezi-7d032.firebasestorage.app',
    iosBundleId: 'com.example.bitirmetezimobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeByybyjT666Ygk-ZFSUM96gm7SyeSkM',
    appId: '1:344041336788:ios:3483b80531c864587db041',
    messagingSenderId: '344041336788',
    projectId: 'bitirmetezi-7d032',
    storageBucket: 'bitirmetezi-7d032.firebasestorage.app',
    iosBundleId: 'com.example.bitirmetezimobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABY0_S6loAbNHJAjxUjCLzXpT2i1ypstY',
    appId: '1:344041336788:web:0e9e8958ddddbed67db041',
    messagingSenderId: '344041336788',
    projectId: 'bitirmetezi-7d032',
    authDomain: 'bitirmetezi-7d032.firebaseapp.com',
    storageBucket: 'bitirmetezi-7d032.firebasestorage.app',
    measurementId: 'G-NKSKJ0R74B',
  );
}
